apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  namespace: asadev
  labels:
    app: springapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      name: springpod
      labels:
        app: springapp
    spec:
      containers:
      - name: springappcon
        image: asadevprac/springbootmongo:1
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongosvc
        - name: MONGO_DB_USERNAME
          value: devdb
        - name: MONGO_DB_PASSWORD
          value: dev123
---
apiVersion: v1
kind: Service
metadata:
  name: springappsvc
  namespace: asadev
spec:
  type: NodePort
  selector:
    app: springapp
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodbrs
  namespace: asadev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongodb
      labels:
        app: mongo
    spec:
      containers:
      - name: mongocon
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: devdb
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: dev123
             
---
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
  namespace: asadev
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
